import { Injectable } from '@angular/core';
import { Observable } from 'rxjs/Observable';
import { of } from 'rxjs/observable/of';
import { catchError, map, tap } from 'rxjs/operators';
import { AlertService } from './index';
import * as _ from 'lodash';
import { State } from '../../models/state';
import { City } from '../../models/city';

@Injectable()
export class LocationService {
  public STATES: State[] = [
    {id: 1,  name: 'Johor'},
    {id: 2,  name: 'Kedah'},
    {id: 3,  name: 'Kelantan'},
    {id: 4,  name: 'Kuala Lumpur'},
    {id: 5,  name: 'Labuan'},
    {id: 6,  name: 'Melaka'},
    {id: 7,  name: 'Negeri Sembilan'},
    {id: 8,  name: 'Pahang'},
    {id: 9,  name: 'Putrajaya'},
    {id: 10,  name: 'Perlis'},
    {id: 11,  name: 'Pulau Pinang'},
    {id: 12,  name: 'Perak'},
    {id: 13,  name: 'Sabah'},
    {id: 14,  name: 'Sarawak'},
    {id: 15,  name: 'Selangor'},
    {id: 16,  name: 'Terengganu'}
  ]

  public CITIES: City[] = [
    {id: 1, state_id: 1, name: 'Ayer Baloi'},
    {id: 2, state_id: 1, name: 'Ayer Hitam'},
    {id: 3, state_id: 1, name: 'Ayer Tawar 3'},
    {id: 4, state_id: 1, name: 'Bandar Penawar'},
    {id: 5, state_id: 1, name: 'Bandar Tenggara'},
    {id: 6, state_id: 1, name: 'Batu Anam'},
    {id: 7, state_id: 1, name: 'Batu Pahat'},
    {id: 8, state_id: 1, name: 'Bekok'},
    {id: 9, state_id: 1, name: 'Benut'},
    {id: 10, state_id: 1, name: 'Bukit Gambir'},
    {id: 11, state_id: 1, name: 'Bukit Pasir'},
    {id: 12, state_id: 1, name: 'Chaah'},
    {id: 13, state_id: 1, name: 'Endau'},
    {id: 14, state_id: 1, name: 'Gelang Patah'},
    {id: 15, state_id: 1, name: 'Gerisek'},
    {id: 16, state_id: 1, name: 'Gugusan Taib Andak'},
    {id: 17, state_id: 1, name: 'Jementah'},
    {id: 18, state_id: 1, name: 'Johor Bahru'},
    {id: 19, state_id: 1, name: 'Kahang'},
    {id: 20, state_id: 1, name: 'Kluang'},
    {id: 21, state_id: 1, name: 'Kota Tinggi'},
    {id: 22, state_id: 1, name: 'Kukup'},
    {id: 23, state_id: 1, name: 'Kulai'},
    {id: 24, state_id: 1, name: 'Labis'},
    {id: 25, state_id: 1, name: 'Layang-Layang'},
    {id: 26, state_id: 1, name: 'Masai'},
    {id: 27, state_id: 1, name: 'Mersing'},
    {id: 28, state_id: 1, name: 'Muar'},
    {id: 29, state_id: 1, name: 'Nusajaya'},
    {id: 30, state_id: 1, name: 'Pagoh'},
    {id: 31, state_id: 1, name: 'Paloh'},
    {id: 32, state_id: 1, name: 'Panchor'},
    {id: 33, state_id: 1, name: 'Parit Jawa'},
    {id: 34, state_id: 1, name: 'Parit Raja'},
    {id: 35, state_id: 1, name: 'Parit Sulong'},
    {id: 36, state_id: 1, name: 'Pasir Gudang'},
    {id: 37, state_id: 1, name: 'Pengerang'},
    {id: 38, state_id: 1, name: 'Pontian'},
    {id: 39, state_id: 1, name: 'Rengam'},
    {id: 40, state_id: 1, name: 'Rengit'},
    {id: 41, state_id: 1, name: 'Segamat'},
    {id: 42, state_id: 1, name: 'Semerah'},
    {id: 43, state_id: 1, name: 'Senai'},
    {id: 44, state_id: 1, name: 'Senggarang'},
    {id: 45, state_id: 1, name: 'Seri Gading'},
    {id: 46, state_id: 1, name: 'Simpang Rengam'},
    {id: 47, state_id: 1, name: 'Sri Medan'},
    {id: 48, state_id: 1, name: 'Sungai Mati'},
    {id: 49, state_id: 1, name: 'Tangkak'},
    {id: 50, state_id: 1, name: 'Ulu Tiram'},
    {id: 51, state_id: 1, name: 'Yong Peng'},
		{id: 52, state_id: 2, name: 'Alor Setar'},
		{id: 53, state_id: 2, name: 'Alor Star'},
		{id: 54, state_id: 2, name: 'Ayer Hitam'},
		{id: 55, state_id: 2, name: 'Baling'},
		{id: 56, state_id: 2, name: 'Bandar Baharu'},
		{id: 57, state_id: 2, name: 'Bandar Bahru'},
		{id: 58, state_id: 2, name: 'Bedong'},
		{id: 59, state_id: 2, name: 'Bukit Kayu Hitam'},
		{id: 60, state_id: 2, name: 'Gurun'},
		{id: 61, state_id: 2, name: 'Jeniang'},
		{id: 62, state_id: 2, name: 'Jitra'},
		{id: 63, state_id: 2, name: 'Karangan'},
		{id: 64, state_id: 2, name: 'Kepala Batas'},
		{id: 65, state_id: 2, name: 'Kodiang'},
		{id: 66, state_id: 2, name: 'Kota Kuala Muda'},
		{id: 67, state_id: 2, name: 'Kota Sarang Semut'},
		{id: 68, state_id: 2, name: 'Kuala Kedah'},
		{id: 69, state_id: 2, name: 'Kuala Ketil'},
		{id: 70, state_id: 2, name: 'Kuala Nerang'},
		{id: 71, state_id: 2, name: 'Kuala Pegang'},
		{id: 72, state_id: 2, name: 'Kulim'},
		{id: 73, state_id: 2, name: 'Kupang'},
		{id: 74, state_id: 2, name: 'Langgar'},
		{id: 75, state_id: 2, name: 'Langkawi'},
		{id: 76, state_id: 2, name: 'Lunas'},
		{id: 77, state_id: 2, name: 'Merbok'},
		{id: 78, state_id: 2, name: 'Padang Serai'},
		{id: 79, state_id: 2, name: 'Pendang'},
		{id: 80, state_id: 2, name: 'Pokok Sena'},
		{id: 81, state_id: 2, name: 'Serdang'},
		{id: 82, state_id: 2, name: 'Sik'},
		{id: 83, state_id: 2, name: 'Simpang Empat'},
		{id: 84, state_id: 2, name: 'Sungai Petani'},
		{id: 85, state_id: 2, name: 'Universiti Utara Malaysia'},
		{id: 86, state_id: 2, name: 'Yan'},
    {id: 87, state_id: 3, name: 'Ayer Lanas'},
    {id: 88, state_id: 3, name: 'Bachok'},
    {id: 89, state_id: 3, name: 'Cherang Ruku'},
    {id: 90, state_id: 3, name: 'Dabong'},
    {id: 91, state_id: 3, name: 'Gua Musang'},
    {id: 92, state_id: 3, name: 'Jeli'},
    {id: 93, state_id: 3, name: 'Kem Desa Pahlawan'},
    {id: 94, state_id: 3, name: 'Ketereh'},
    {id: 95, state_id: 3, name: 'Kota Bahru'},
    {id: 96, state_id: 3, name: 'Kota Bharu'},
    {id: 97, state_id: 3, name: 'Kuala Balah'},
    {id: 98, state_id: 3, name: 'Kuala Krai'},
    {id: 99, state_id: 3, name: 'Machang'},
    {id: 100, state_id: 3, name: 'Melor'},
    {id: 101, state_id: 3, name: 'Pasir  Puteh'},
    {id: 102, state_id: 3, name: 'Pasir Mas'},
    {id: 103, state_id: 3, name: 'Pulai Chondong'},
    {id: 104, state_id: 3, name: 'Rantau Panjang'},
    {id: 105, state_id: 3, name: 'Selising'},
    {id: 106, state_id: 3, name: 'Tanah Merah'},
    {id: 107, state_id: 3, name: 'Temangan'},
    {id: 108, state_id: 3, name: 'Tumpat'},
    {id: 109, state_id: 3, name: 'Wakaf Bharu'},
		{id: 110, state_id: 4, name: 'Batu Caves'},
		{id: 111, state_id: 4, name: 'Cheras'},
		{id: 112, state_id: 4, name: 'Kuala Lumpur'},
		{id: 113, state_id: 4, name: 'Setapak'},
		{id: 114, state_id: 5, name: 'Labuan'},
		{id: 115, state_id: 6, name: 'Alor Gajah'},
		{id: 116, state_id: 6, name: 'Asahan'},
		{id: 117, state_id: 6, name: 'Ayer Keroh'},
		{id: 118, state_id: 6, name: 'Durian Tunggal'},
		{id: 119, state_id: 6, name: 'Jasin'},
		{id: 120, state_id: 6, name: 'Kem Trendak'},
		{id: 121, state_id: 6, name: 'Kuala Sungai Baru'},
		{id: 122, state_id: 6, name: 'Lubok China'},
		{id: 123, state_id: 6, name: 'Masjid Tanah'},
		{id: 124, state_id: 6, name: 'Melaka'},
		{id: 125, state_id: 6, name: 'Merlimau'},
		{id: 126, state_id: 6, name: 'Selandar'},
		{id: 127, state_id: 6, name: 'Sungai Rambai'},
		{id: 129, state_id: 6, name: 'Sungai Udang'},
		{id: 131, state_id: 7, name: 'Bahau'},
		{id: 132, state_id: 7, name: 'Bandar Baru Enstek'},
		{id: 133, state_id: 7, name: 'Bandar Seri Jempol'},
		{id: 134, state_id: 7, name: 'Batu Kikir'},
		{id: 135, state_id: 7, name: 'Gemas'},
		{id: 136, state_id: 7, name: 'Gemencheh'},
		{id: 137, state_id: 7, name: 'Johol'},
		{id: 138, state_id: 7, name: 'Kota'},
		{id: 139, state_id: 7, name: 'Kuala Klawang'},
		{id: 140, state_id: 7, name: 'Kuala Pilah'},
		{id: 141, state_id: 7, name: 'Labu'},
		{id: 142, state_id: 7, name: 'Linggi'},
		{id: 143, state_id: 7, name: 'Mantin'},
		{id: 144, state_id: 7, name: 'Nilai'},
		{id: 145, state_id: 7, name: 'Port Dickson'},
		{id: 146, state_id: 7, name: 'Pusat  Bandar Palong'},
		{id: 147, state_id: 7, name: 'Rantau'},
		{id: 148, state_id: 7, name: 'Rembau'},
		{id: 149, state_id: 7, name: 'Rompin'},
		{id: 150, state_id: 7, name: 'Seremban'},
		{id: 151, state_id: 7, name: 'Si Rusa'},
		{id: 152, state_id: 7, name: 'Simpang Durian'},
		{id: 153, state_id: 7, name: 'Simpang Pertang'},
		{id: 154, state_id: 7, name: 'Tampin'},
		{id: 155, state_id: 7, name: 'Tanjong Ipoh'},
		{id: 156, state_id: 8, name: 'Balok'},
		{id: 157, state_id: 8, name: 'Bandar Pusat  Jengka'},
		{id: 158, state_id: 8, name: 'Bandar Pusat Jengka'},
		{id: 159, state_id: 8, name: 'Bandar Tun Abdul Razak'},
		{id: 160, state_id: 8, name: 'Benta'},
		{id: 161, state_id: 8, name: 'Bentong'},
		{id: 162, state_id: 8, name: 'Brinchang'},
		{id: 163, state_id: 8, name: 'Bukit Fraser'},
		{id: 164, state_id: 8, name: 'Bukit Goh'},
		{id: 165, state_id: 8, name: 'Chenor'},
		{id: 166, state_id: 8, name: 'Chini'},
		{id: 167, state_id: 8, name: 'Damak'},
		{id: 168, state_id: 8, name: 'Dong'},
		{id: 169, state_id: 8, name: 'Gambang'},
		{id: 170, state_id: 8, name: 'Genting Highlands'},
		{id: 171, state_id: 8, name: 'Jaya Gading'},
		{id: 172, state_id: 8, name: 'Jerantut'},
		{id: 173, state_id: 8, name: 'Karak'},
		{id: 174, state_id: 8, name: 'Kemayan'},
		{id: 175, state_id: 8, name: 'Kuala Krau'},
		{id: 176, state_id: 8, name: 'Kuala Lipis'},
		{id: 177, state_id: 8, name: 'Kuala Rompin'},
		{id: 178, state_id: 8, name: 'Kuantan'},
		{id: 179, state_id: 8, name: 'Lanchang'},
		{id: 180, state_id: 8, name: 'Lurah Bilut'},
		{id: 181, state_id: 8, name: 'Mentakab'},
		{id: 182, state_id: 8, name: 'Muadzam Shah'},
		{id: 183, state_id: 8, name: 'Padang Tengku'},
		{id: 184, state_id: 8, name: 'Pekan'},
		{id: 185, state_id: 8, name: 'Raub'},
		{id: 186, state_id: 8, name: 'Ringlet'},
		{id: 187, state_id: 8, name: 'Sega'},
		{id: 188, state_id: 8, name: 'Sungai Koyan'},
		{id: 189, state_id: 8, name: 'Sungai Lembing'},
		{id: 190, state_id: 8, name: 'Tanah Rata'},
		{id: 191, state_id: 8, name: 'Temerloh'},
		{id: 192, state_id: 8, name: 'Triang'},
		{id: 193, state_id: 9, name: 'Putrajaya'},
		{id: 194, state_id: 10, name: 'Arau'},
		{id: 195, state_id: 10, name: 'Kaki Bukit'},
		{id: 196, state_id: 10, name: 'Kangar'},
		{id: 197, state_id: 10, name: 'Kuala Perlis'},
		{id: 198, state_id: 10, name: 'Padang Besar'},
		{id: 199, state_id: 10, name: 'Simpang Ampat'},
		{id: 200, state_id: 11, name: 'Ayer Itam'},
		{id: 201, state_id: 11, name: 'Balik Pulau'},
		{id: 202, state_id: 11, name: 'Batu Ferringhi'},
		{id: 203, state_id: 11, name: 'Batu Maung'},
		{id: 204, state_id: 11, name: 'Bayan Lepas'},
		{id: 205, state_id: 11, name: 'Bukit Mertajam'},
		{id: 206, state_id: 11, name: 'Butterworth'},
		{id: 207, state_id: 11, name: 'Gelugor'},
		{id: 208, state_id: 11, name: 'Jelutong'},
		{id: 209, state_id: 11, name: 'Kepala Batas'},
		{id: 210, state_id: 11, name: 'Kubang Semang'},
		{id: 211, state_id: 11, name: 'Nibong Tebal'},
		{id: 212, state_id: 11, name: 'Penaga'},
		{id: 213, state_id: 11, name: 'Penang Hill'},
		{id: 214, state_id: 11, name: 'Perai'},
		{id: 215, state_id: 11, name: 'Permatang Pauh'},
		{id: 216, state_id: 11, name: 'Pulau Pinang'},
		{id: 217, state_id: 11, name: 'Simpang Ampat'},
		{id: 218, state_id: 11, name: 'Tanjong Bungah'},
		{id: 219, state_id: 11, name: 'Tasek Gelugor'},
		{id: 220, state_id: 11, name: 'Tasek Gelugur'},
		{id: 221, state_id: 11, name: 'USM Pulau Pinang'},
    {id: 222, state_id: 12, name: 'Ayer Tawar'},
    {id: 223, state_id: 12, name: 'Bagan Datoh'},
    {id: 224, state_id: 12, name: 'Bagan Serai'},
    {id: 225, state_id: 12, name: 'Bandar Seri Iskandar'},
    {id: 226, state_id: 12, name: 'Batu Gajah'},
    {id: 227, state_id: 12, name: 'Batu Kurau'},
    {id: 228, state_id: 12, name: 'Behrang Stesen'},
    {id: 229, state_id: 12, name: 'Bidor'},
    {id: 230, state_id: 12, name: 'Bruas'},
    {id: 231, state_id: 12, name: 'Changkat Jering'},
    {id: 232, state_id: 12, name: 'Changkat Keruing'},
    {id: 233, state_id: 12, name: 'Chemor'},
    {id: 234, state_id: 12, name: 'Chenderiang'},
    {id: 235, state_id: 12, name: 'Chenderong Balai'},
    {id: 236, state_id: 12, name: 'Chikus'},
    {id: 237, state_id: 12, name: 'Enggor'},
    {id: 238, state_id: 12, name: 'Gerik'},
    {id: 239, state_id: 12, name: 'Gopeng'},
    {id: 240, state_id: 12, name: 'Hutan Melintang'},
    {id: 241, state_id: 12, name: 'Intan'},
    {id: 242, state_id: 12, name: 'Ipoh'},
    {id: 243, state_id: 12, name: 'Jeram'},
    {id: 244, state_id: 12, name: 'Kampar'},
    {id: 245, state_id: 12, name: 'Kampung Gajah'},
    {id: 246, state_id: 12, name: 'Kampung Kepayang'},
    {id: 247, state_id: 12, name: 'Kamunting'},
    {id: 248, state_id: 12, name: 'Kuala Kangsar'},
    {id: 249, state_id: 12, name: 'Kuala Kurau'},
    {id: 250, state_id: 12, name: 'Kuala Sepetang'},
    {id: 251, state_id: 12, name: 'Lambor Kanan'},
    {id: 252, state_id: 12, name: 'Langkap'},
    {id: 253, state_id: 12, name: 'Lenggong'},
    {id: 254, state_id: 12, name: 'Lumut'},
    {id: 255, state_id: 12, name: 'Malim Nawar'},
    {id: 256, state_id: 12, name: 'Mambang Di Awan'},
    {id: 257, state_id: 12, name: 'Manong'},
    {id: 258, state_id: 12, name: 'Matang'},
    {id: 259, state_id: 12, name: 'Padang Rengas'},
    {id: 260, state_id: 12, name: 'Pangkor'},
    {id: 261, state_id: 12, name: 'Pantai Remis'},
    {id: 262, state_id: 12, name: 'Parit'},
    {id: 263, state_id: 12, name: 'Parit Buntar'},
    {id: 264, state_id: 12, name: 'Pengkalan Hulu'},
    {id: 265, state_id: 12, name: 'Pusing'},
    {id: 266, state_id: 12, name: 'Rantau Panjang'},
    {id: 267, state_id: 12, name: 'Sauk'},
    {id: 268, state_id: 12, name: 'Selama'},
    {id: 269, state_id: 12, name: 'Selekoh'},
    {id: 270, state_id: 12, name: 'Seri Manjung'},
    {id: 271, state_id: 12, name: 'Simpang'},
    {id: 272, state_id: 12, name: 'Simpang Ampat Semanggol'},
    {id: 273, state_id: 12, name: 'Sitiawan'},
    {id: 274, state_id: 12, name: 'Slim River'},
    {id: 275, state_id: 12, name: 'Sungai Siput'},
    {id: 276, state_id: 12, name: 'Sungai Sumun'},
    {id: 277, state_id: 12, name: 'Sungkai'},
    {id: 278, state_id: 12, name: 'TLDM Lumut'},
    {id: 279, state_id: 12, name: 'Taiping'},
    {id: 280, state_id: 12, name: 'Tanjong Malim'},
    {id: 281, state_id: 12, name: 'Tanjong Piandang'},
    {id: 282, state_id: 12, name: 'Tanjong Rambutan'},
    {id: 283, state_id: 12, name: 'Tanjong Tualang'},
    {id: 284, state_id: 12, name: 'Tapah'},
    {id: 285, state_id: 12, name: 'Tapah Road'},
    {id: 286, state_id: 12, name: 'Teluk Intan'},
    {id: 287, state_id: 12, name: 'Temoh'},
    {id: 288, state_id: 12, name: 'Trolak'},
    {id: 289, state_id: 12, name: 'Trong'},
    {id: 290, state_id: 12, name: 'Tronoh'},
    {id: 291, state_id: 12, name: 'Ulu Bernam'},
    {id: 292, state_id: 12, name: 'Ulu Kinta'},
		{id: 293, state_id: 13, name: 'Beaufort'},
		{id: 294, state_id: 13, name: 'Beluran'},
		{id: 295, state_id: 13, name: 'Beverly'},
		{id: 296, state_id: 13, name: 'Bongawan'},
		{id: 297, state_id: 13, name: 'Inanam'},
		{id: 298, state_id: 13, name: 'Keningau'},
		{id: 299, state_id: 13, name: 'Kota Belud'},
		{id: 300, state_id: 13, name: 'Kota Kinabalu'},
		{id: 301, state_id: 13, name: 'Kota Kinabatangan'},
		{id: 302, state_id: 13, name: 'Kota Marudu'},
		{id: 303, state_id: 13, name: 'Kuala Penyu'},
		{id: 304, state_id: 13, name: 'Kudat'},
		{id: 305, state_id: 13, name: 'Kunak'},
		{id: 306, state_id: 13, name: 'Lahad Datu'},
		{id: 307, state_id: 13, name: 'Likas'},
		{id: 308, state_id: 13, name: 'Membakut'},
		{id: 309, state_id: 13, name: 'Menumbok'},
		{id: 310, state_id: 13, name: 'Nabawan'},
		{id: 311, state_id: 13, name: 'Pamol'},
		{id: 312, state_id: 13, name: 'Papar'},
		{id: 313, state_id: 13, name: 'Penampang'},
		{id: 314, state_id: 13, name: 'Putatan'},
		{id: 315, state_id: 13, name: 'Ranau'},
		{id: 316, state_id: 13, name: 'Sandakan'},
		{id: 317, state_id: 13, name: 'Semporna'},
		{id: 318, state_id: 13, name: 'Sipitang'},
		{id: 319, state_id: 13, name: 'Tambunan'},
		{id: 320, state_id: 13, name: 'Tamparuli'},
		{id: 321, state_id: 13, name: 'Tanjung Aru'},
		{id: 322, state_id: 13, name: 'Tawau'},
		{id: 323, state_id: 13, name: 'Tenghilan'},
		{id: 324, state_id: 13, name: 'Tenom'},
		{id: 325, state_id: 13, name: 'Tuaran'},
		{id: 326, state_id: 14, name: 'Asajaya'},
		{id: 327, state_id: 14, name: 'Balingian'},
		{id: 328, state_id: 14, name: 'Baram'},
		{id: 329, state_id: 14, name: 'Bau'},
		{id: 330, state_id: 14, name: 'Bekenu'},
		{id: 331, state_id: 14, name: 'Belaga'},
		{id: 332, state_id: 14, name: 'Belawai'},
		{id: 333, state_id: 14, name: 'Betong'},
		{id: 334, state_id: 14, name: 'Bintangor'},
		{id: 335, state_id: 14, name: 'Bintulu'},
		{id: 336, state_id: 14, name: 'Dalat'},
		{id: 337, state_id: 14, name: 'Daro'},
		{id: 338, state_id: 14, name: 'Debak'},
		{id: 339, state_id: 14, name: 'Engkilili'},
		{id: 340, state_id: 14, name: 'Julau'},
		{id: 341, state_id: 14, name: 'Kabong'},
		{id: 342, state_id: 14, name: 'Kanowit'},
		{id: 343, state_id: 14, name: 'Kapit'},
		{id: 344, state_id: 14, name: 'Kota Samarahan'},
		{id: 345, state_id: 14, name: 'Kuching'},
		{id: 346, state_id: 14, name: 'Lawas'},
		{id: 347, state_id: 14, name: 'Limbang'},
		{id: 348, state_id: 14, name: 'Lingga'},
		{id: 349, state_id: 14, name: 'Long Lama'},
		{id: 350, state_id: 14, name: 'Lubok Antu'},
		{id: 351, state_id: 14, name: 'Lundu'},
		{id: 352, state_id: 14, name: 'Lutong'},
		{id: 353, state_id: 14, name: 'Matu'},
		{id: 354, state_id: 14, name: 'Miri'},
		{id: 355, state_id: 14, name: 'Mukah'},
		{id: 356, state_id: 14, name: 'Nanga Medamit'},
		{id: 357, state_id: 14, name: 'Niah'},
		{id: 358, state_id: 14, name: 'Pusa'},
		{id: 359, state_id: 14, name: 'Roban'},
		{id: 360, state_id: 14, name: 'Saratok'},
		{id: 361, state_id: 14, name: 'Sarikei'},
		{id: 362, state_id: 14, name: 'Sebauh'},
		{id: 363, state_id: 14, name: 'Sebuyau'},
		{id: 364, state_id: 14, name: 'Serian'},
		{id: 365, state_id: 14, name: 'Sibu'},
		{id: 366, state_id: 14, name: 'Siburan'},
		{id: 367, state_id: 14, name: 'Simunjan'},
		{id: 368, state_id: 14, name: 'Song'},
		{id: 369, state_id: 14, name: 'Spaoh'},
		{id: 370, state_id: 14, name: 'Sri Aman'},
		{id: 371, state_id: 14, name: 'Sundar'},
		{id: 372, state_id: 14, name: 'Tatau'},
		{id: 373, state_id: 15, name: 'Ampang'},
		{id: 374, state_id: 15, name: 'Bandar Baru Bangi'},
		{id: 375, state_id: 15, name: 'Bandar Puncak Alam'},
		{id: 376, state_id: 15, name: 'Bangi'},
		{id: 377, state_id: 15, name: 'Banting'},
		{id: 378, state_id: 15, name: 'Batang Berjuntai'},
		{id: 379, state_id: 15, name: 'Batang Kali'},
		{id: 380, state_id: 15, name: 'Beranang'},
		{id: 381, state_id: 15, name: 'Bukit Rotan'},
		{id: 382, state_id: 15, name: 'Cheras'},
		{id: 383, state_id: 15, name: 'Cyberjaya'},
		{id: 384, state_id: 15, name: 'Dengkil'},
		{id: 385, state_id: 15, name: 'Hulu Langat'},
		{id: 386, state_id: 15, name: 'Jenjarom'},
		{id: 387, state_id: 15, name: 'Jeram'},
		{id: 388, state_id: 15, name: 'KLIA'},
		{id: 389, state_id: 15, name: 'Kajang'},
		{id: 390, state_id: 15, name: 'Kapar'},
		{id: 391, state_id: 15, name: 'Kerling'},
		{id: 392, state_id: 15, name: 'Klang'},
		{id: 393, state_id: 15, name: 'Kuala Kubu Baru'},
		{id: 394, state_id: 15, name: 'Kuala Selangor'},
		{id: 395, state_id: 15, name: 'Pelabuhan Klang'},
		{id: 396, state_id: 15, name: 'Petaling Jaya'},
		{id: 397, state_id: 15, name: 'Puchong'},
		{id: 398, state_id: 15, name: 'Pulau Carey'},
		{id: 399, state_id: 15, name: 'Pulau Ketam'},
		{id: 400, state_id: 15, name: 'Rasa'},
		{id: 401, state_id: 15, name: 'Rawang'},
		{id: 402, state_id: 15, name: 'Sabak Bernam'},
		{id: 403, state_id: 15, name: 'Sekinchan'},
		{id: 404, state_id: 15, name: 'Semenyih'},
		{id: 405, state_id: 15, name: 'Sepang'},
		{id: 406, state_id: 15, name: 'Serdang'},
		{id: 407, state_id: 15, name: 'Serendah'},
		{id: 408, state_id: 15, name: 'Seri Kembangan'},
		{id: 409, state_id: 15, name: 'Shah Alam'},
		{id: 410, state_id: 15, name: 'Subang Airport'},
		{id: 411, state_id: 15, name: 'Subang Jaya'},
		{id: 412, state_id: 15, name: 'Sungai Ayer Tawar'},
		{id: 413, state_id: 15, name: 'Sungai Besar'},
		{id: 414, state_id: 15, name: 'Sungai Buloh'},
		{id: 415, state_id: 15, name: 'Sungai Pelek'},
		{id: 416, state_id: 15, name: 'Tanjong Karang'},
		{id: 417, state_id: 15, name: 'Tanjong Sepat'},
		{id: 418, state_id: 15, name: 'Telok Panglima Garang'},
    {id: 419, state_id: 16, name: 'Ajil'},
    {id: 420, state_id: 16, name: 'Al Muktatfi Billah Shah'},
    {id: 421, state_id: 16, name: 'Bukit Besi'},
    {id: 422, state_id: 16, name: 'Bukit Payong'},
    {id: 423, state_id: 16, name: 'Ceneh'},
    {id: 424, state_id: 16, name: 'Chalok'},
    {id: 425, state_id: 16, name: 'Cukai'},
    {id: 426, state_id: 16, name: 'Dungun'},
    {id: 427, state_id: 16, name: 'Jerteh'},
    {id: 428, state_id: 16, name: 'Kampung Raja'},
    {id: 429, state_id: 16, name: 'Kemasek'},
    {id: 430, state_id: 16, name: 'Kerteh'},
    {id: 431, state_id: 16, name: 'Ketengah Jaya'},
    {id: 432, state_id: 16, name: 'Kijal'},
    {id: 433, state_id: 16, name: 'Kuala Berang'},
    {id: 434, state_id: 16, name: 'Kuala Besut'},
    {id: 435, state_id: 16, name: 'Kuala Terengganu'},
    {id: 436, state_id: 16, name: 'Marang'},
    {id: 437, state_id: 16, name: 'Paka'},
    {id: 438, state_id: 16, name: 'Permaisuri'},
    {id: 439, state_id: 16, name: 'Sungai Tong'}
  ]
  constructor() {  }

  getStates(): Observable<State[]> {
    return of(this.STATES);
  }

  getStateId(stateName): number {
    let state = _.find(this.STATES, ['name', stateName])

    return state.id;
  }

  getCities(state): Observable<City[]> {
    let state_id = this.getStateId(state);
    let cities = _.filter(this.CITIES, ['state_id', state_id])

    return of(cities);
  }

}
